# Generated by Django 3.2.8 on 2021-10-27 06:23
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=64, unique=True, verbose_name="Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("thumbnail_url", models.URLField(blank=True, verbose_name="Thumbnail URL")),
            ],
            options={"verbose_name_plural": "Areas", "ordering": ["title"]},
        ),
    ]
