# Generated by Django 3.2.8 on 2021-10-27 06:23
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = [("lecturers", "0001_initial"), ("areas", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("thumbnail_url", models.URLField(verbose_name="Thumbnail URL")),
                ("start_datetime", models.DateTimeField(db_index=True, verbose_name="Start Date & Time")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="areas.area", verbose_name="Area"
                    ),
                ),
                ("lectures", models.ManyToManyField(to="lecturers.Lecturer", verbose_name="Event Authors")),
            ],
            options={"verbose_name_plural": "Events", "ordering": ["-modified"]},
        ),
    ]
